# Generated by Django 5.2 on 2025-04-27 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Profile creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Profile last updated timestamp')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('name', models.CharField(blank=True, help_text='Display name for the user', max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('other_info', models.CharField(blank=True, help_text='Additional infromation', max_length=255)),
                ('user', models.OneToOneField(blank=True, help_text='The user this profile belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the task', max_length=255)),
                ('description', models.TextField(help_text='Detailed description of the task')),
                ('due_date', models.DateField(help_text='Deadline for the task')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], help_text='Priority level of the task', max_length=20)),
                ('category', models.CharField(blank=True, help_text='Optional category for grouping tasks', max_length=100, null=True)),
                ('files', models.FileField(blank=True, help_text='Optional file attachment related to the task', null=True, upload_to='task_files')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the task was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the task was last updated')),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('done', 'Done')], default='pending', help_text='Current state of the task', max_length=20)),
                ('assigned_users', models.ManyToManyField(help_text='Users assigned to this task', related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
