# Generated by Django 5.2 on 2025-04-29 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productivity_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='state',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='file',
        ),
    ]
