# Generated by Django 5.2 on 2025-04-29 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productivity_app', '0002_rename_state_task_status_remove_profile_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='description',
            new_name='task_description',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='title',
            new_name='task_title',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='files',
            new_name='upload_files',
        ),
    ]
