# Generated by Django 5.2 on 2025-04-29 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productivity_app', '0003_rename_description_task_task_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='task_title',
            new_name='title',
        ),
    ]
