# Generated by Django 5.2 on 2025-04-29 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productivity_app', '0004_rename_task_description_task_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='description',
            new_name='task_description',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='title',
            new_name='task_title',
        ),
    ]
