# Generated by Django 5.2 on 2025-04-25 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productivity_app', '0005_remove_userprofile_avatar_remove_userprofile_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='settings',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
