# Generated by Django 5.2 on 2025-05-02 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productivity_app', '0006_taskfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='task_title',
            new_name='title',
        ),
        migrations.DeleteModel(
            name='TaskFile',
        ),
    ]
