# Generated by Django 5.2 on 2025-04-25 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productivity_app', '0006_alter_userprofile_settings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='settings',
            new_name='other_info',
        ),
    ]
