# Generated by Django 5.2 on 2025-05-03 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productivity_app', '0007_rename_task_description_task_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='other_info',
        ),
    ]
