# Generated by Django 5.2 on 2025-04-25 15:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productivity_app', '0007_rename_settings_userprofile_other_info'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='assigned_users',
            field=models.ManyToManyField(related_name='user_profiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
