# Generated by Django 5.2 on 2025-05-06 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productivity_app', '0008_remove_profile_other_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(blank=True, choices=[('development', 'Development'), ('design', 'Design'), ('testing', 'Testing'), ('documentation', 'Documentation'), ('other', 'Other')], help_text='Optional category for grouping tasks', max_length=100, null=True),
        ),
    ]
