# Generated by Django 5.2 on 2025-04-25 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productivity_app', '0008_userprofile_assigned_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='assigned_users',
        ),
    ]
