# Generated by Django 5.2 on 2025-04-25 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productivity_app', '0010_task_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
